name: Redeploy Job

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      instance-name:
        required: true
        type: string
    secrets:
      nomad-token:
        required: true
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Redeploy job on instance
      if: ${{ github.ref == 'refs/heads/develop' && (inputs.image-name == 'frontend' || inputs.image-name == 'dpu') }}
      env:
        NOMAD_TOKEN: ${{ secrets.nomad-token }}
        INSTANCE_ADDRESS: https://${{ inputs.instance-name }}.monolithai.app:4646 # could store this as secret
      run: |
        echo ${{ inputs.image-name }}
        echo ${{ github.ref }}
        # Read job job and save response to json file
        curl --header "X-Nomad-Token: ${{ env.NOMAD_TOKEN }}" ${{ env.INSTANCE_ADDRESS }}/v1/job/${{ inputs.image-name }} | jq '{Job: .}' > ReadJob.json
        # Stop running job
        curl -X DELETE --header "X-Nomad-Token: ${{ env.NOMAD_TOKEN }}" ${{ env.INSTANCE_ADDRESS }}/v1/job/${{ inputs.image-name }}
        # Re-start the job with the job json file
        curl -X POST --header "X-Nomad-Token: ${{ env.NOMAD_TOKEN }}" -d @ReadJob.json ${{ env.INSTANCE_ADDRESS }}/v1/jobs
      