name: SonarCloud Scan

on:
  workflow_call:
    secrets:
      ci-read-gh-token:
        required: true
      sonar-token:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.ci-read-gh-token }}
        SONAR_TOKEN: ${{ secrets.sonar-token }}