name: Test Image

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.10.1
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build test image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build . --target '${{ inputs.target }}'
